import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { PostList } from "../components";
import { trpc } from "../utils/trpc";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};


const Home: NextPage = () => {

  const hello = trpc.useQuery(["example.hello"]);
  const hello2 = trpc.useQuery(["question.hello"]);
  const posts = trpc.useQuery(["posts.getPosts"]);
  const { data } = useSession();
  console.log(data)
  return (
    <>
      <Head>
        <title>Twotter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">Posts</h1>

        <PostList posts={posts.data}/>

      </main>
    </>
  );
};



export default Home;
